DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  address_id INT NOT NULL UNIQUE,
  meter_id INT NOT NULL UNIQUE
);

DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  street_name VARCHAR(250) NOT NULL,
  street_number VARCHAR(250) NOT NULL,
  city VARCHAR(250) NOT NULL,
  CONSTRAINT UC_ADDRESS UNIQUE (street_name, street_number, city)
);

DROP TABLE IF EXISTS METER;

CREATE TABLE METER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  serial_number VARCHAR(32) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS METER_READING;

CREATE TABLE METER_READING (
  id INT AUTO_INCREMENT PRIMARY KEY,
  meter_id INT NOT NULL,
  month VARCHAR(2) NOT NULL,
  year VARCHAR(4) NOT NULL,
  reading INT NOT NULL,
  CONSTRAINT UC_METER_READING UNIQUE (meter_id, month, year)
);

